# Generated by Django 5.0.1 on 2026-03-29 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("First_name", models.CharField(max_length=16)),
                ("Last_name", models.CharField(max_length=16)),
                ("email", models.EmailField(max_length=255)),
            ],
        ),
    ]
